### ISSUE TITLE
Cannot retrieve unique frames

### ISSUE THREAD

**Issue by Keboland108** [esrf-bliss/Lima-camera-dhyana#1]
When using the conda python interface, following the code example found below:

[getting-started](https://lima1.readthedocs.io/en/latest/camera/dhyana/doc/index.html#getting-started)

and attempting to read a frame beyond frame 0 (for example reading frame 1) I am getting the following error
``` console
limacore.Exception: Control: readBlock(/opt/conda/conda-bld/lima-core_1648541428893/work/control/src/CtControl.cpp, 887): Error: Frame(s) not available yet
```

Is there a way to get more control over frames using the Python interface?

**Comment by laurent-claustre** [comment]
Hi,
did you really set nb frames to 10 before calling prepareAcq() and startAcq()? you can check by calling acq.getAcqNbFrames()

**Comment by Keboland108** [comment]
Hi,

Thank you for the response. That approach worked! 

Regards
